### ISSUE TITLE
В системе отсутствует русскоязычная озвучка!\nОбратитесь к автору программы за 

### ISSUE THREAD

**Issue by Radzhab** [tpltn/Speaker#7]
Тимур) пчму так?

**Comment by tpltn** [comment]
@Radzhab попробуйте установить 
http://www.microsoft.com/en-us/download/details.aspx?id=27225 
а затем 
http://www.microsoft.com/en-us/download/details.aspx?id=27224 
* MSSpeech_TTS_ru-RU_Elena.msi

**Comment by Radzhab** [comment]
чувствую венду надо перевесить

**Comment by tpltn** [comment]
@Radzhab у вас какой язык системы?

**Comment by Radzhab** [comment]
у меня русский

**Comment by tpltn** [comment]
А в Панели управления => Распознавание речи => Диктор? есть среди языков хотя бы один русский?
